name: build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure 