name: build
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
      - uses: actions/upload-artifact@7
        with:
          name: binary
          path: build/main 

  run:
    needs: build-and-test
    runs-on: ubuntu-24.04
    steps: 
      - uses: actions/download-artifact@7
        with:
          name: binary
      - run: chmod +x main && ./main 12 13